### PR TITLE
Add international identifiers

### PR DESCRIPTION
**Pull request by denismaier**
This adds a couple of new international identifiers, as per https://github.com/citation-style-language/csl-evolution/issues/39#issue-624996102

ISWC (for a musical work itself)
ISMN (for a musical notation/score)
ISRC (for an audio or visual recording)
ISAN (for an audiovisual work itself)
ISCI (an identifier for an archival collection)

These are ISO identifiers analogous to ISSN and ISBN. These appear to be important for citation and cataloging in fields like musicology (e.g., citation-style-language/zotero-bits#28).

Fixes: https://github.com/citation-style-language/csl-evolution/issues/39

### CODE REVIEW

**Comment by bdarcus** [comment]
Need to update your branch. 

See this article, which may suggest `git pull --rebase` is better than merge?

**Comment by denismaier** [comment]
I've opened a new PR based on current upstream.

**Comment by bwiernik** [comment]
You don't need to close/reopen PRs for that. Just run `git pull --rebase` or `git rebase <hash>` instead.

**Comment by denismaier** [comment]
> You don't need to close/reopen PRs for that. Just run `git pull --rebase` or `git rebase <hash>` instead.

Thanks. Next time then...

**Pull request closed without merging**
