### PR TITLE
Add new variables for minor release

### PR DESCRIPTION
**Pull request by bwiernik**
Gone through most of the issues in zotero-bits. Just a few that still need some thinking there. Still need to process schema, documentation, and csl-evolution

Closes https://github.com/citation-style-language/schema/issues/157 actor
Closes https://github.com/citation-style-language/schema/issues/179 part and part-title
Closes https://github.com/citation-style-language/schema/issues/163 available-date
Closes https://github.com/citation-style-language/schema/issues/114 contributor

Addresses https://github.com/citation-style-language/zotero-bits/issues/43 compiler
Addresses https://github.com/citation-style-language/zotero-bits/issues/27 archive_collection
Addresses https://github.com/citation-style-language/csl-evolution/issues/22 archive_collection
Addresses https://github.com/citation-style-language/zotero-bits/issues/60 chair and organizer
Addresses https://github.com/citation-style-language/zotero-bits/issues/44 supplement
Addresses https://github.com/citation-style-language/zotero-bits/issues/32 division

### CODE REVIEW

**Comment by bwiernik** [comment]
Not done yet.

**Comment by bdarcus** [comment]
Note: you can mark a PR a "draft."

**Comment by bwiernik** [comment]
Right, forgot about that.

**Comment by bdarcus** [comment]
It's now a draft. Just hit "ready for review" when done.

I can't tell from the current commit message what is actually being submitted currently. No doubt this is in part of the somewhat vague github keywords.

Here's a [good resource on git commit messages](https://chris.beams.io/posts/git-commit/); though I realize I've been violating one of his rules!

Also, in the future, if in doubt, I think it's arguably better to split into multiple commits, rather than one larger one, because we can always easily squash when merging, but can't do the reverse.

So, for example, end up with commits like `Add "compiler" variable`; could even bundle a few together like that without the commit message getting too long.

**Comment by bwiernik** [comment]
yes

**Comment by bwiernik** [comment]
@bdarcus Let's go ahead and merge this. Can add more in a different PR. I can't see what the conflicts are because I don't have write access

**Comment by bdarcus** [comment]
> @bdarcus Let's go ahead and merge this. Can add more in a different PR. I can't see what the conflicts are because I don't have write access

I can't see them either.

Did you run `git merge master`? If not, do that; will likely fix the conflicts.

**Comment by bdarcus** [comment]
Nevermind; I see you did.

**Comment by bwiernik** [comment]
Yeah I did and it didn't report any conflicts

**Comment by bdarcus** [comment]
Try this, from your master branch:

``` console
$ git remote add upstream https://github.com/citation-style-language/schema.git

# you may need to run `git fetch upstream master`; not sure

$ git pull upstream master
$ git checkout new-variables
$ git merge master
```
It works for me on a local copy of your repo.

**Comment by bwiernik** [comment]
Fetching was the step I was missing.

**Comment by bdarcus** [comment]
Note I merged this to a branch, to see if I can figure out how to clean up the history. Might take m a little time to figure it out.

Definitely easier (for me at least) if you can keep PRs more focused; allows me to just quickly squash merge.

Or if not, you can use interactive rebase yourself on your branch to rewrite the history.

**Comment by bwiernik** [comment]
@bdarcus if you just want to squash a PR, there is a dropdown menu on the merge button.

**Comment by bdarcus** [comment]
I'm aware. But I didn't know what was going on with all the commits so that I could figure out what the commit message would be, until I started digging into it.

**Comment by bdarcus** [comment]
PS - apologies @bwiernik - it seems what I did erased your authorship of the changes. But I did link to your original PR on the commit summary.

**Pull request merged**
