### PR TITLE
Add new terms

### PR DESCRIPTION
**Pull request by bwiernik**
## Description

Add various new terms needed for APA, MLA, or other styles or to match new variables added to CSL 1.0.2.

The change in of `article` to `article-locator` is because we have the `article` type as well. 

A few questions:
1. Thinking about `"no-name"`, since is is used to mean "no-publisher", should we just call it that, even though the Latin literally means "no name"?
2. I'd like to be able to have a term for both "review of" and "review of the" to be able to accomodate both of these situations:
    - `Review of "Strangers on a Train"`
    - `Review of the film "Strangers on a Train"`

    Could we add `form="with-article"` and `form="with-article-short"` to meet that? Data conventions in languages with gendered articles are to store the article in the data, whereas in English article aren't stored in the data (cf. the `presented at` term includes an article in the `en` locales, but not in the `fr` locales).
3. Do we want to remove the "category" terms now or in 1.1?
4. Should we fix the `sub verbo` term bug now or stick with the solution Rintze created?

Closes https://github.com/citation-style-language/schema/issues/103
Closes https://github.com/citation-style-language/csl-evolution/issues/34

## Type of change

Please delete options that are not relevant.

- [X] Variable addition (adds a new variable or type string)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by bwiernik** [comment]
@bdarcus I don't understand what this check means:
```
 Check schema formatting0s
  shell: /bin/bash -e {0}
Run for f in csl*.rnc; do diff -q $f schemas/styles/$f ; done
  for f in csl*.rnc; do diff -q $f schemas/styles/$f ; done
  shell: /bin/bash -e {0}
Files csl-terms.rnc and schemas/styles/csl-terms.rnc differ
```

**Comment by denismaier** [comment]
> ## Description
> Add various new terms needed for APA, MLA, or other styles or to match new variables added to CSL 1.0.2.
> 
> The change in of `article` to `article-locator` is because we have the `article` type as well.
> 
> A few questions:
> 
> 1. Thinking about `"no-name"`, since is is used to mean "no-publisher", should we just call it that, even though the Latin literally means "no name"?


> 2. I'd like to be able to have a term for both "review of" and "review of the" to be able to accomodate both of these situations:
>    
>    * `Review of "Strangers on a Train"`
>    * `Review of the film "Strangers on a Train"`
>    
>    Could we add `form="with-article"` and `form="with-article-short"` to meet that? Data conventions in languages with gendered articles are to store the article in the data, whereas in English article aren't stored in the data (cf. the `presented at` term includes an article in the `en` locales, but not in the `fr` locales).

Something like this is definitively needed, yes- But this deserves perhaps its own issue.

> 3. Do we want to remove the "category" terms now or in 1.1?
It seems we are already on the way to 1.1. So it should be 1.1.

> 4. Should we fix the `sub verbo` term bug now or stick with the solution Rintze created?

I'd say this should be fixed. (I'll submit a PR)

> 
> Closes #103
> Closes [citation-style-language/csl-evolution#34](https://github.com/citation-style-language/csl-evolution/issues/34)
> 
> ## Type of change
> Please delete options that are not relevant.
> 
> * [x]  Variable addition (adds a new variable or type string)
> * [ ]  This change requires a documentation update

**Comment by denismaier** [comment]
> * Thinking about `"no-name"`, since is is used to mean "no-publisher", should we just call it that, even though the Latin literally means "no name"?

So you're saying this is not indended for works without an author? (I now there's the term anonymous, but I'm not sure this is 100% the same thing as `no-author`.

**Comment by bwiernik** [comment]
Yes, sine nomine (what `no-name` was added to cover) is used to mean "no publisher", not "no author": https://en.wikipedia.org/wiki/Sine_nomine

**Comment by denismaier** [comment]
So, then let's just call it `no-publisher`.

**Comment by bdarcus** [comment]
> So, then let's just call it `no-publisher`.

Yes, let's avoid latin unless necessary.

**Comment by bdarcus** [comment]
I just tried to change the base branch to `v1.1`, but it resulted in the earlier problem of a ton of other commits. I don't really understand.

**Comment by bwiernik** [comment]
Can we just merge this into 1.0.2 and cut a new 1.0.2pre2 tag?

**Comment by bdarcus** [comment]
I think yes, for this one.

Do you why this happened?

Because you branches off master?

**Comment by bwiernik** [comment]
Yes, when master is merged into v1.1 (or vice versa), there will be some conflicts that need to be resolved.

**Comment by bdarcus** [comment]
Yes, I am aware.

One of the reasons I'll be happy to get that merged and hopefully just
focus on master going forward.

**Comment by bwiernik** [comment]
I'm happy to do the resolution once we do the gold cut of 1.0.2 and merge 1.1 into master

**Pull request merged**
