### PR TITLE
add additional locator variables

### PR DESCRIPTION
**Pull request by denismaier**
This adds the additional locator types needed according to @bwiernik's proposal: https://github.com/citation-style-language/schema/issues/166

These are:
table
equation
appendix
supplement
timestamp
location (as in for e-readers)
article
rule
title
canon

### CODE REVIEW

**Comment by denismaier** [comment]
I can't link this PR to the issue that this closes.

**Comment by bdarcus** [comment]
> I can't link this PR to the issue that this closes.

Not necessary, as github will auto close when merged.

**Comment by bwiernik** [comment]
Should we rename `sub verbo` to `sub-verbo` as well at this point? I believe the breakage discussed here is still an issue? https://github.com/citation-style-language/schema/issues/72

**Comment by denismaier** [comment]
Wait, I'll close this one and create another from a new branch

**Comment by bwiernik** [comment]
Add the word "closes" before the issue link

**Comment by bdarcus** [comment]
Why are you closing? If you want to change the commit message, just do `git commit --amend`.

**Comment by bwiernik** [comment]
(He opened from the wrong branch in his fork.)

Note that to edit the commit message after the first line (the "commit comment"), you can also do that in the Github.com interface, rather than having to use `git commit --amend`

**Comment by rmzelle** [comment]
(replaced by https://github.com/citation-style-language/schema/pull/201)

**Pull request closed without merging**
