### PR TITLE
Reformat readme for improved aesthetics

### PR DESCRIPTION
**Pull request by dhimmel**
use one sentence per line to improve git diffs.

### CODE REVIEW

**Comment by bdarcus** [comment]
Can you say a little more, for people that might edit the README in the future?

What's the editor setting we want to avoid using; the equivalent of auto-fill on emacs?

**Comment by dhimmel** [comment]
> Can you say a little more, for people that might edit the README in the future?

This PR does many types of small formatting changes, but generally they'd be picked up by a markdown linter. Other changes are using the right element types for things, for example heading levels and `code`.

Regarding one sentence per line, the idea is described at https://rhodesmill.org/brandon/2012/one-sentence-per-line/. The idea is to place source newlines between phrases or sentences. It's not supported by most automatic markdown formatters, but they generally leave line breaks alone. So just when editing or adding to the README, it's best if contributors use one sentence per line.

**Comment by bdarcus** [comment]
Thanks.

Markdownlint is complaining about a few things, the most relevant of which is probably line length. What do you make of that? In the article you linked, he breaks lines, and starts each sentence on a new line.

**Comment by bdarcus** [comment]
Seems to be issues with that too related to trailing whitespace.

**Comment by dhimmel** [comment]
I would disable the line length warning. Most text editors wrap long lines, so there's not actually a problem with long sentences on a single line.

> Seems to be issues with that too related to trailing whitespace.

we don't want trailing whitespace (unless rare case when its used for `<br>`). Sorry if I added any of this.

**Comment by bdarcus** [comment]
No problem; am just asking.

**Pull request merged**
