### PR TITLE
Add terms for "no-place" and "no-name"

### PR DESCRIPTION
**Pull request by denismaier**
Closes https://github.com/citation-style-language/schema/issues/138

### CODE REVIEW

**Comment by bdarcus** [comment]
Just bumping this @denismaier; see question above.

**Comment by bwiernik** [comment]
```
no-place: indicates place of publication is unlisted or unknown
no-name: indicates publisher is unlisted or unknown
```

cf.
https://en.wikipedia.org/wiki/Sine_nomine
https://en.wikipedia.org/wiki/List_of_Latin_phrases_(S)#sine_loco

**Comment by bdarcus** [comment]
Perfect; thanks!

This raises another minor question; should we do "no name" or "no-name"?

I know we have a lot of existing terms that are not tokens, but that "sub verbo" issue makes me leery about that.

**Comment by bwiernik** [comment]
Let's adopt an all-token approach "just in case". I've been thinking about a proposal lately that might be much easier if terms were reliably tokens.

**Comment by denismaier** [comment]
Will do tomorrow. 
What about "no date"? Change that to "no-date" as well? I've actually had the all-token version at first, but changed it to the version without hyphens because of "no date"

**Comment by bdarcus** [comment]
> Will do tomorrow.
> What about "no date"? Change that to "no-date" as well? I've actually had the all-token version at first, but changed it to the version without hyphens because of "no date"

I made the changes on the first two.

Is "no date" new, so no legacy?

**Comment by bdarcus** [comment]
Actually, no it's not new. 

So let's hold off on that now. Perhaps we can contemplate a retroactive fix as a separate step.

**Comment by denismaier** [comment]
No. It's not new.
I'd say we clean this up later together with the other non-token terms, but having "no date" next to "no-place" is particularly ugly.

**Comment by bdarcus** [comment]
Yeah, I know.

It's a big schema, that's now almost 15 years old, so there's going to
be some ugly corners.

Hopefully we can clean this up sooner rather than later.

**Pull request merged**
