### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by bdarcus**
Not really sure exactly what these should be in the end, but this is a start.

It's designed to address the biggest thing historically missing from issue requests (missing context, including style guide links). 

Note, though, I only tweaked the default template, so not sure.

Please review this "feature request" template, and also weigh in on if you think we need others (like "bug report"), and if so, what the content should be.

### CODE REVIEW

**Comment by bdarcus** [comment]
I have two approval to merge as is, without adding a bug report template.

Any other thoughts?

**Comment by denismaier** [comment]
I am not sure we need a bug template. I first thought we could something like this:

---
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Tested with:**
 - OS: [e.g. Windows 10]
 - Reference Manager [e.g. Zotero, Mendeley]
 - Word processor

**Additional context**
Add any other context about the problem here.
---

But probably, this will give us mostly reports about bugs in certain implementations.

**Comment by bdarcus** [comment]
IF we added a bug template, we would want to make clear that it's only for mistakes in the schemas.

For example, #225.

**Comment by bwiernik** [comment]
I think asking casual contributors to discern between "issues" and "bugs" is likely to be more of a headache than it's worth.

**Pull request merged**
