### PR TITLE
create definitions for name-variable and date-variable

### PR DESCRIPTION
**Pull request by dhimmel**
closes https://github.com/citation-style-language/schema/issues/188

https://json-schema.org/understanding-json-schema/structuring.html

### CODE REVIEW

**Comment by dhimmel** [comment]
ready for review. my text editor made a bunch of whitespace changes that complicate the diff. Not ideal but we probably those changes.

**Comment by dhimmel** [comment]
@dsifford, I think this solves the issue mentioned at https://github.com/citation-style-language/schema/pull/187#issuecomment-632665522.

**Comment by bdarcus** [comment]
Thanks @dhimmel - so should I merge now, or wait on @dsifford to review?

**Comment by dsifford** [comment]
LGTM

**Comment by dhimmel** [comment]
@bdarcus GitHub's rebase merge option is probably not ideal for PRs like this one. Squash merge is nice since it makes everything in a single commit. Regular merge is also nice because the merge commit groups all commits from the PR together. With the rebase-merge it's not clear what commits were part of the PR and you lose the ability to have a commit message with the PR title / description.

Not big deal, just wanted to share my insights if they're helpful in future. Thanks for maintaining this repo!

**Comment by dsifford** [comment]
I always squash unless there is a ton of commits and there's a chance I'd need to `git bisect` to find a bug. 99% of the time I squash though.

**Comment by bdarcus** [comment]
I appreciate it.

So bottomline, don't use rebase-merge at all, and probably default to squash-merge?

**Comment by dhimmel** [comment]
> So bottomline, don't use rebase-merge at all, and probably default to squash-merge?

yes. squash merge unless there is a reason to keep the PR commits separate. Reasons include multiple authors or very large PRs where squashing would conflate too many unrelated changes (but try to avoid these PRs in general). I'd say 95% of the time, squash merge is best. And if pull requests are generally kept simple and straightforward, that's closer to 100%.

**Pull request merged**
