### PR TITLE
update to iso-schematron, add macro dup check

### PR DESCRIPTION
**Pull request by bdarcus**
This combines #129 with an update to ISO Schematron.

### CODE REVIEW

**Comment by rmzelle** [comment]
@bdarcus, thanks. Did you have any plans to maintain a changelog? (I guess we can also label these PRs with a milestone label so we can compile a changelog before release)

**Comment by bdarcus** [comment]
I tried to write the commit messages so it'd be straightforward to add
content to a changelog, potentially (hopefully) even automatically via a
script.

**Comment by bdarcus** [comment]
Actually, it's easy enough to manually create it. I put a draft release with changelog here.

https://github.com/citation-style-language/schema/releases

**Comment by rmzelle** [comment]
@bdarcus, did you check your ISO Schematron schema to see if it works with Jing? The new version broke https://validator.citationstyles.org/, which relies on https://github.com/validator/validator/wiki/Service-%C2%BB-HTTP-interface, which in turn uses Jing.

Compare

https://validator.w3.org/nu/?doc=https://gist.githubusercontent.com/rmzelle/0e95202f2b261cc98de507b1254bac08/raw/2aa04910af5be9150673f851b89425949eaf3055/apa-test.csl&schema=https://raw.githubusercontent.com/citation-style-language/schema/602ad40976b7b455a3ce0b79f5534e8e75f088e9/csl.sch&parser=xml&laxtype=yes&level=error&out=json&showsource=yes

(old csl.sch)

to

https://validator.w3.org/nu/?doc=https://gist.githubusercontent.com/rmzelle/0e95202f2b261cc98de507b1254bac08/raw/2aa04910af5be9150673f851b89425949eaf3055/apa-test.csl&schema=https://raw.githubusercontent.com/citation-style-language/schema/2bbf44f8eb51f9ed5fa2cc84f319d8e4833a4174/csl.sch&parser=xml&laxtype=yes&level=error&out=json&showsource=yes

(new csl.sch)

**Comment by bdarcus** [comment]
Jing doesn't support iso schematron yet apparently. I tested with some other validator that did support it.

Do we control the csl validator?

And is it using the external sch file, or the embedded rules (so just csl.rnc)?

If the former, then couldn't we change it to use the [url for the earlier version](https://raw.githubusercontent.com/citation-style-language/schema/602ad40976b7b455a3ce0b79f5534e8e75f088e9/csl.sch).

Or I could rollback the change on this file, and add a separate `csl-iso.sch` one.

**Comment by rmzelle** [comment]
> Do we control the csl validator?

Yes (I made it): https://github.com/citation-style-language/csl-validator

> And is it using the external sch file, or the embedded rules (so just csl.rnc)?

The former. IIRC, Jing doesn't parse embedded Schematron, so I had it pointed to both csl.rnc and csl.sch.

> If the former, then couldn't we change it to use the [url for the earlier version](https://raw.githubusercontent.com/citation-style-language/schema/602ad40976b7b455a3ce0b79f5534e8e75f088e9/csl.sch).

Yes, that's what I come up with too as the quickest fix: https://github.com/citation-style-language/csl-validator/commit/8a7395d27cdf0e40009cd8c2c6dd6baefa68c3d1.

**Comment by rmzelle** [comment]
(anyway, I mostly asked to make sure the new csl.sch is valid Schematron. We can stick with ISO going forward)

**Comment by bdarcus** [comment]
FWIW, for this simple schema, the only difference between the two is:

1) I had to remove the sch:name element (not valid in iso)

2) the different namespace URI

**Pull request merged**
