### PR TITLE
Extend date era formatting options

### LINKED ISSUE #124: AD/BC (better: CE/BCE): terms, position of AD/AH, separating space
The specs regarding calendar era (http://citationstyles.org/downloads/specification.html#ad-and-bc) are incorrect on two points, and problematic on another one:
(1) There should always be a (protected) space between year and term (Chicago Manual of Style, 16th ed., 9.35 “Eras”).
(2) “Note that the Latin abbreviations AD and AH precede the year number, whereas the others follow it.” (Chicago Manual of Style, 16th ed., 9.35 “Eras”). – Examples from the Chicago Manual:

> Herod Antipas (21 BCE–39 CE) was tetrarch of Galilee from 4 BCE until his death.
> Britain was invaded successfully in 55 BC and AD 1066.

(3) “AD/BC” is increasingly regarded as culturally and religiously insensitive. As a default, “AD/BC” should be replaced by the more neutral “CE/BCE”, and the “ad” and “bc” term labels should also be replaced by “ce” and “bce”. – I’d just like to quote Kofi Annan here:

> [T]he Christian calendar no longer belongs exclusively to Christians. People of all faiths have taken to using it simply as a matter of convenience. There is so much interaction between people of different faiths and cultures – different civilizations, if you like – that some shared way of reckoning time is a necessity. And so the Christian Era has become the Common Era. (Quoted in https://en.wikipedia.org/wiki/Common_Era)

### PR DESCRIPTION
**Pull request by denismaier**
## Description

Currently, CSL only supports AD/BC to designate date eras. There is a demand for making this customizable. Also: Placements of these terms must be configurable as AD usually precedes the number, whereas BCE, CE, and BC appear after the number.

This is based on per @bwiernik's [suggestion](https://github.com/citation-style-language/schema/issues/124#issuecomment-634052815), slightly adjusted:

1. Add new terms `ce` and `bce`.

2. To switch between systems, we add a new localized style option `era-notation` which can take values `"ce"` (default) or `"ad"`. These switch between using CE/BCE and AD/BC respectively.

3. To control placement of era terms, `cs:date` gets a `cs:era` child element (similar to `cs:et-al`). This takes the form:
`<era term="ad"/>`
`<era term="bc ce bce"/>`

This indicates the placement of the terms in a date (if present). Terms are a space delimited list. `cs:era` can take text formatting attributes. 

So, total changes:
- add terms `ce` and `bce`
- add `cs:era` element 
- add `era-notation` attribute to `cs:style-options`

Fixes #124  (issue)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist

- [X] I have installed the repo [pre-commit hook](https://github.com/citation-style-language/schema/blob/master/CONTRIBUTING.md#pre-commit-hooks); if not, and I have modified any of the schema files, I have run trang and/or prettier on the files, per [CONTRIBUTING](https://github.com/citation-style-language/schema/blob/master/CONTRIBUTING.md)
- [X] I have performed a self-review of my own code
- [] I have included suggested corresponding changes to the documentation (if relevant)

### CODE REVIEW

**Comment by denismaier** [comment]
Why doesn't that work? @bdarcus?

**Comment by bwiernik** [comment]
```
Err:2 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 openjdk-11-jre-headless amd64 11.0.7+10-2ubuntu2~18.04
  404  Not Found [IP: 52.168.50.79 80]
Err:5 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 openjdk-11-jre amd64 11.0.7+10-2ubuntu2~18.04
  404  Not Found [IP: 52.168.50.79 80]
...
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jre-headless_11.0.7+10-2ubuntu2~18.04_amd64.deb  404  Not Found [IP: 52.168.50.79 80]
Fetched 13.4 MB in 9s (1524 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openjdk-lts/openjdk-11-jre_11.0.7+10-2ubuntu2~18.04_amd64.deb  404  Not Found [IP: 52.168.50.79 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
##[error]Process completed with exit code 100.
```

Having a problem installing some of the OpenJDK dependencies.

**Comment by bdarcus** [comment]
When an Action fails like that, you can "re-run" the job manually, as I just did.

**Comment by bdarcus** [comment]
An example where we need one or more tests for the test-suite.

Otherwise, is this RTM?

**Pull request merged**
