### PR TITLE
CSL JSON Data schema: add custom field

### PR DESCRIPTION
**Pull request by dhimmel**
closes https://github.com/citation-style-language/schema/issues/277

let me know if any other files need to be changed. I added `title` and `description` as per #190. Hopefully we can eventually auto-generate CSL JSON docs from this... but are there docs that need to be updated manually now?

### CODE REVIEW

**Comment by bdarcus** [comment]
Thanks!

This is currently set to merge to master, feasibly for 1.0.2, which I am tagging today.

Should we do this now, or for 1.1?

I'm agnostic.

@bwiernik and @denismaier can answer your questions, as I'm unsure.

**Comment by dhimmel** [comment]
> This is currently set to merge to master, feasibly for 1.0.2, which I am tagging today.

It is backwards compatible (as far as I can tell), so not huge harm. But it is a new feature, so if you want to follow semantic versioning, it would go in the next MINOR release... but I am guessing much of the stuff in 1.0.2 is actually new features and not backcompat bug fixes.

**Comment by bdarcus** [comment]
> I am guessing much of the stuff in 1.0.2 is actually new features and not backcompat bug fixes.

1.0.2 is mostly new variables and types; strings.

**Comment by denismaier** [comment]
As it seems, semantic versioning does not really work as is for xml schemas, due to validation and so. Or at least, we haven't figured out how to do it properly... ;-)
So yeah 1.0.2 adds new features, but requires relatively minor changes in processors.

**Comment by denismaier** [comment]
Concerning the script: we shouldn't worry about this now. I'm not so sure we will need this if we adopt `@related` and "sub/main" as forms. These will solve the same sort of problems the script was trying to solve. But anyway, adapting the script will be easy enough.

**Comment by dhimmel** [comment]
> Concerning the script: we shouldn't worry about this now. I'm not so sure we will need this if we adopt @related and "sub/main" as forms. These will solve the same sort of problems the script was trying to solve.

Ah cool. Just made a related post at https://github.com/citation-style-language/schema/issues/223#issuecomment-650258108.

**Comment by bdarcus** [comment]
Partly for marketing reasons, then, how about we add this to 1.1?

**Comment by dhimmel** [comment]
> Partly for marketing reasons, then, how about we add this to 1.1?

Fine with me. I think as time goes on, you might want to go with just MANOR.MINOR since we don't really have the concept of PATCHES for this project.

No rush on my end to have this official

**Comment by dhimmel** [comment]
Changing the base branch to v1.1 messed stuff up.

@bdarcus is that the correct branch to merge to? If so, I fix this PR so it's only one commit?

**Comment by bdarcus** [comment]
> Changing the base branch to v1.1 messed stuff up.
> 
> @bdarcus is that the correct branch to merge to? If so, I fix this PR so it's only one commit?

Yes. I ran into the same problem a few days ago; did we do something wrong with that branch or something?

**Comment by dhimmel** [comment]
> I ran into the same problem a few days ago; did we do something wrong with that branch or something?

Well currently v1.1 is "27 commits ahead, 23 commits behind master.". But since v1.1 hasn't been released yet, I don't think v1.1 branch needs to exist yet and all new work should be going in master. `v1.0` should accumulate commits that will just go into `v1.0.2`.

But it seems like this won't be the case for 1.1. So will switch to the 1.1 branch.

**Comment by bdarcus** [comment]
So we did it backwards; should have done minor work on the 1.0 branch, and major work on master.

> But it seems like this won't be the case for 1.1. So will switch to the 1.1 branch.

Could/should we fix this now?

I was planning to tag a 1.0.2-pre and give some time for feedback.

So should I merge master to 1.0, and tag there, and then merge 1.1 to master?

**Comment by dhimmel** [comment]
> So we did it backwards; should have done minor work on the 1.0 branch, and more major work on master.

Yes. Oftentimes, you might just be picking commits from master to cherry-pick onto the `1.0.2` branch. Everything goes into master, and then stuff is back-ported that needs to be. In the future, it's probably easiest if you don't have to upkeep old versions, because the process is annoying.

> Could/should we fix this now?

Sounds like 1.0.2 is coming out soon. Maybe wait until 1.0.2 is released. After that you can merge 1.1 into master and then get rid of 1.1 until you are ready to release it.

**Comment by bdarcus** [comment]
OK, I just updated the 1.0 branch and tagged v1.0.2-pre.1 there. Is
that part right, or do I also need to tag on master?

We'll hold off a bit on merging 1.1.

**Comment by dhimmel** [comment]
> OK, I just updated the 1.0 branch and tagged v1.0.2-pre.1 there.

That is good.

> Is that part right, or do I also need to tag on master?

No. I don't think tags point to a branch at all. They point to a commit hash. If that commit is on v.1.0 and master, the tag doesn't specify which particular branch. That being said, a 1.0.* tag should point to a commit that exists on the v.1.0 branch.

**Comment by bwiernik** [comment]
Yeah, think of tags as signposts. "This is the point you should regard as the v1.0.2-pre.1 release."

**Pull request merged**
