### PR TITLE
Ignore rng

### PR DESCRIPTION
**Pull request by denismaier**
I suggest we add `*.rng` to `.gitignore` so we don't have to worry about rng-files after `trang csl.rnc csl.rng`.

### CODE REVIEW

**Comment by bdarcus** [comment]
Yes, I was thing about that yesterday.

But the script should also delete them when done.

**Comment by denismaier** [comment]
> But the script should also delete them when done.

Really, should it?
I see only two commands in the script:

```
trang csl.rnc csl.rng
trang csl.rng csl.rnc
```

rng-files remain there.

**Comment by denismaier** [comment]
I don't know, but perhaps there is a command line parameter.
Or just `rm *.rng`?

**Comment by bdarcus** [comment]
Sorry; my wording was vague.

I meant to say I need to revise it to do that.

**Comment by denismaier** [comment]
Ok then.

**Comment by bdarcus** [comment]
Thanks. I just added it directly, since I got a little confused about the three commits on this PR.

**Comment by rmzelle** [comment]
(done in https://github.com/citation-style-language/schema/commit/0a1f43a38a60e4266c1eccafcc7e1bc7622a5715)

**Pull request closed without merging**
