### PR TITLE
Reconcile v1.1 with v1.0.2

### PR DESCRIPTION
**Pull request by bwiernik**
## Description

Merge v1.0.2 into v1.1 and resolve conflicts.

### CODE REVIEW

**Comment by bdarcus** [comment]
Thanks. After you run trang on csl-choose, I presume we should merge this now?

**Comment by bdarcus** [comment]
Tip: if you use the script, or run trang on the main csl.rnc file, it will also format the included ones.

**Comment by bwiernik** [comment]
I haven't been able to get the pre-commit hook to work on my system. It never completes. I ran trang on all of the rnc files. Thanks for the tip on the main csl.rnc.

**Comment by bdarcus** [comment]
> I haven't been able to get the pre-commit hook to work on my system.

That's good to know; I was wondering.

Did you get any meaningful error messages?

On git, am I doing a standard merge commit; not a squash commit?

If the former, do you want to rebase the last two formatting fixes for a cleaner history?

Or shall I just merge as is?

**Comment by bwiernik** [comment]
One thing I wonder is why trang wasn't concerned about some of these line breaks before when they were committed on the master branch?

**Comment by bwiernik** [comment]
No error messages, just never hanged.

**Comment by bdarcus** [comment]
I wonder if it's possible there's a version mismatch between what we use
and what's on Ubuntu (which is what the CI uses)?

Granted, trang is pretty stable, so I doubt it.

**Comment by bdarcus** [comment]
The current script isn't supposed to fail; it's supposed to silently fix
the formatting.

**Comment by bwiernik** [comment]
I'll rebase against master and trang everything instead.

**Pull request closed without merging**
