### PR TITLE
specify details for strip-url-protocol

### PR DESCRIPTION
**Pull request by denismaier**
I can't push directly to your PR @bwiernik, so I'll add this this way.

### CODE REVIEW

**Comment by bwiernik** [comment]
Lgtm

**Comment by bwiernik** [comment]
What's the failed test?

**Comment by denismaier** [comment]
let's see if running trang makes the test successful...

**Comment by denismaier** [comment]
yes... (lesson learned: don't use the online editor on github even for simple changes.)

**Comment by bdarcus** [comment]
> I can't push directly to your PR @bwiernik, so I'll add this this way.

For future reference, you can also do line comment suggestions. See item 6 in [this section](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request).

**Comment by denismaier** [comment]
> > I can't push directly to your PR @bwiernik, so I'll add this this way.
> 
> For future reference, you can also do line comment suggestions. See item 6 in [this section](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request).

I've tried that as well, but those line comment suggestions seem to be only possible somewhere near the lines that were changed by the original PR, not somewhere else in the file. (E.g., in this case I could have added this suggestion around line 856, but not were they should end up.)

**Pull request merged**
