### PR TITLE
CI: Add a check for schema formatting

### PR DESCRIPTION
**Pull request by bdarcus**
This addition to the CI tests simply checks if changes to the rnc and 
json schema files conform to our formatting expectations.

### CODE REVIEW

**Comment by denismaier** [comment]
Nice. So no CI needed, right? Will this be installed automatically? Also, if there is no trang this will throw errors. And of course, it needs bash...

**Comment by bdarcus** [comment]
> Nice. So no CI needed, right? Will this be installed automatically? Also, if there is no trang this will throw errors. And of course, it needs bash...

We still need CI, because this relies on people to install the hook themselves.

It will either throw an error, or simply not do the check. I didn't check.

It's not a very smart script.

The pre-commit project seems like a better option, as I mentioned, where we could do something, say, with python, and so some additional stuff.

But my coding skills are minimal.

**Comment by bdarcus** [comment]
I decided to remove the hook and put it in #247.

**Comment by dhimmel** [comment]
> Could do the same for the json schema, but that may be less important. Do we want this? Argument in favor: should avoid any funky diffs or whitespace-related merge conflicts.

I think so. It makes sense to enforce a style when multiple people are collaborating on a single JSON or XML file. If I remember from the past, we had some messy diffs due to trailing whitespace... would have been best to prevent that whitespace from ever getting merged.

**Comment by bdarcus** [comment]
> > Could do the same for the json schema, but that may be less important. Do we want this? Argument in favor: should avoid any funky diffs or whitespace-related merge conflicts.
> 
> I think so. It makes sense to enforce a style when multiple people are collaborating on a single JSON or XML file. If I remember from the past, we had some messy diffs due to trailing whitespace... would have been best to prevent that whitespace from ever getting merged.

Yeah, my thought as well.

On the pre-commit hook, I'm using the default prettier hook for formatting json files.

Do you know of a similarly simple analog for what [I'm doing to check the rnc files](https://github.com/citation-style-language/schema/pull/247/files#diff-afb7705aa4398060eff1c01d7007947dR29)?

Need to install prettier, run it on the json files, and then diff the output.

**Comment by dhimmel** [comment]
> Need to install prettier, run it on the json files, and then diff the output.

`prettier --check` looks like it's designed for this application https://prettier.io/docs/en/cli.html#--check

**Comment by bdarcus** [comment]
> > Need to install prettier, run it on the json files, and then diff the output.
> 
> `prettier --check` looks like it's designed for this application https://prettier.io/docs/en/cli.html#--check

And what's the best way to install prettier itself on the action config?

**Comment by dhimmel** [comment]
> what's the best way to install prettier itself on the action config

I think you can add the step:

```yaml
- uses: actions/setup-node@v1
```

Then probably just install prettier via one of these methods https://prettier.io/docs/en/install.html

You could do this in a new job or one of the existing jobs.

**Comment by bdarcus** [comment]
OK, thanks.

Looks like I got it working.

**Pull request merged**
